adding stripe modular example
openfga/sample-stores pull request #29
Opened 2024-05-30 22:06 UTC by tylernix

## Description
This example models a few of Stripe's core functionality, but not everything.
It introduces another [modular models](https://openfga.dev/docs/modeling/modular-models) example splitting the model into 3 modules:
- `accounts.fga` - core Stripe account functionality
- `payments.fga` - (yet to be implemented)
- `issuing.fga` - credit card issuing and transactions

It also introduces modeling concepts such as "self-defining" relationships, "dual-write" relationships, and "intermediate" relationships. It also uses exclusions and conditions. 

It includes tests for two scenarios:
1. SCENARIO 1: An account manages 2 cards, assigned to users Raghd and Jon. Raghd's card is active and makes two purchases. Jon's card is inactive and makes one purchase
2. SCENARIO 2: A Stripe account (in test mode) manages one active card that tries to make a purchase.

[ ] Working on writing a README.md for the sample store.

## Review Checklist
- [ ] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [ ] The correct base branch is being used, if not `main`
- [ ] I have added tests to validate that the change in functionality is working as expected

2024-09-10 13:13 UTC, aaguiarz commented
Let's also add a readme file as in the rest of the examples

2024-09-10 13:13 UTC, aaguiarz requested changes
Added a few comments

2024-09-10 13:13 UTC, aaguiarz commented on stores/stripe/issuing.fga
> +module issuing
Looks like an odd module name. What would be the app component handling this called? "card-management""

2024-09-10 13:13 UTC, aaguiarz commented on stores/stripe/accounts.fga
> +    define test_mode: [account] # self-defining relationship, used to set a type into a true/false state
We should explain in the comments what is test mode used for in Stripe

2024-09-10 13:13 UTC, aaguiarz commented on stores/stripe/issuing.fga
> +        define card: [card] # dual-writes relationships between card & account, when you need to traverse relations on two types checking both ways (starting at card then going up or account then goi
Can you clarify why we need to traverse it both ways?

2024-09-10 13:13 UTC, aaguiarz commented on stores/stripe/issuing.fga
> +condition spending_limit(transaction_amount: double, transaction_limit: double, daily_amount: double, daily_limit: double, monthly_amount: double, monthly_limit: double) {
We should have tuples/tests that use the condition

2026-07-03 19:07 UTC, curfew-marathon commented
This PR has had no human activity for 90 days, so it has been marked `lifecycle/stale`.

This is automated backlog grooming, not a judgment on the work.

What happens next, unless there is activity:
- In 30 days, it will move to `lifecycle/closing-soon`
- 30 days after that, it will be closed

To keep it open, push a commit or leave a comment, and the clock will reset. For work that should not auto-close, such as an RFC or long-running experiment, ask a maintainer to add `lifecycle/frozen`.

<!-- groomfga -->

2026-08-08 01:34 UTC, curfew-marathon commented
This PR has had no human activity for 30 days since being marked `lifecycle/stale`, so it has now been marked `lifecycle/closing-soon`.

It will be closed in 30 days unless there is new activity.

If the work still matters, this is the moment to say so: leave a comment, push a commit, or ask a maintainer to add `lifecycle/frozen` if it should be kept open long-term.

If this work is no longer being pursued, no action is needed.

<!-- groomfga -->

2026-09-12 15:40 UTC, curfew-marathon commented
Closing this after 60 days with no human activity since it was marked `lifecycle/stale`.

This is housekeeping, not a verdict on the change. The work is not lost: if it is still relevant, you can ask for this PR to be reopened or open a fresh PR.

Thanks for putting the time in.

<!-- groomfga -->

2026-09-12 15:40 UTC, closed without merging